### ISSUE TITLE
Gjøre Bash til default shell

### ISSUE THREAD

**Issue by Kyrremann** [navikt/utvikler-ansible#6]
Slik som det er nå, så starter terminalen opp i sh. Det er få som bare jobber i sh, så jeg foreslår at vi legger inn en one liner i `.profile` som starter bash for deg, som login shell.

`test -z "$BASH" && test -x /usr/bin/bash && exec /usr/bin/bash -l`

**Comment by androa** [comment]
Gjerne konfigurerbart, siden jeg kjører zsh :D Men det er heller ikke veldig vondt for meg å bytte selv.

**Comment by Kyrremann** [comment]
Godt poeng.
Kan gjøre dette som en egen playbook, som man kan kjøre etterpå.
Vil det funke å bytte ut `bash` med `zsh` på alle steder?

**Comment by Kyrremann** [comment]
Tror vi dropper denne oppgaven, så kan vi heller dokumentere det i `README.md`. Forslag til linje for zsh?
